version: "3.9"

services:
  db:
    image: postgres:17
    container_name: portfolio-db
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: portfolio-risk-platform
    container_name: portfolio-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/portfolio_db
      SPRING_DATASOURCE_USERNAME: portfolio_user
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"

volumes:
  postgres_data: